### ISSUE TITLE
Difference fields in database and data model

### ISSUE THREAD

**Issue by Mahdimm** [RxSwiftCommunity/RxGRDB#48] opened 2018-11-04 09:44 UTC
Hi @tonyarnold 

I have a table with 3 columns but its model has 4 properties, What should I do in this case? because when I set insert query I got this error:

> Fatal error: 'try!' expression unexpectedly raised an error: SQLite error 1 with statement `INSERT INTO "student" ("id", "name", "lastName", "age") VALUES (?,?,?,?)`: table student has no column named age!

My table columns are: id, name, lastName
My model properties: id, name, lastName, age

is there any protocol that I can fix this problem?

**Comment by groue** [comment] 2018-11-04 14:47
Duplicate of https://github.com/groue/GRDB.swift/issues/438

**Closed by groue** 2018-11-04 14:47 UTC
