### ISSUE TITLE
Can't run RxGRDB in a playground

### ISSUE THREAD

**Issue by kluufger** [RxSwiftCommunity/RxGRDB#31] opened 2018-04-25 17:35 UTC
Hi @groue, sorry for bothering you, but I wonder if you know a possible workaround for a problem I'm facing with using RxGRDB as a git submodule:

💥 Build phase `[CP] Check Pods Manifest.lock` fails with
```plain
diff: /Podfile.lock: No such file or directory
diff: /Manifest.lock: No such file or directory
error: The sandbox is not in sync with the Podfile.lock. Run 'pod install' or update your CocoaPods installation.
```

✅ But if I delete this build phase (`[CP] Check Pods Manifest.lock`), all is good, everything compiles just fine (after I add and build RxSwift and GRDB.swift submodules).

But that means that I modify the `RxGRDB` submodule's source code, which I'm not sure is the cleanest approach ...

**UPDATE**

I've also found this stackoverflow thread https://stackoverflow.com/questions/31901347/restkit-giving-error-after-installation-as-a-git-submodule which suggested some workarounds, will try them out and report back.

1. `pod repo remove master && pod setup` didn't work (not even sure it should've)
2. `pod update` inside `RxGRDB` submodule causes the build to fail with `Apple Mach-O Linker Error`
```plain
ld: warning: directory not found for option '-F/Users/asd/Library/Developer/Xcode/DerivedData/demo-fwpwyrqayjjgnsabixvjddmcgyto/Build/Products/Debug-iphonesimulator/GRDB.swift-iOS'
ld: warning: directory not found for option '-F/Users/asd/Library/Developer/Xcode/DerivedData/demo-fwpwyrqayjjgnsabixvjddmcgyto/Build/Products/Debug-iphonesimulator/RxSwift-iOS'
ld: framework not found Pods_RxGRDBiOS
clang: error: linker command failed with exit code 1 (use -v to see invocation)
```
3. `pod install` would probably cause a linker error just like 2.

**Comment by groue** [comment] 2018-04-25 18:12
Hello @kluufger!

CocoaPods is the only supported [installation method](https://github.com/RxSwiftCommunity/RxGRDB/tree/v0.10.0#installation). I'd be happy to know why you don't... simply use CocoaPods. But let's look at your issue.

The problem is clear. The RxGRDB project contains a CocoaPods-generated build phase, which prevents your build from passing. Indeed, until `pod install` or `pod update` has been run inside the RxGRDB directory, that build phases can't find the required cocoapods artifacts. Furthermore, I don't quite see how a submodule-embedded RxGRDB project will ever be able to build without its companion pod artifacts, since it links to the pod project:

<img width="1072" alt="capture d ecran 2018-04-25 a 19 59 52" src="https://user-images.githubusercontent.com/54219/39263807-87296418-48c3-11e8-9090-6d1dd6838a88.png">

So, I don't know yet what is the best way out. I used to have submodules to GRDB and RxSwift, but it has revealed somewhat painful to manage. I recently switched to CocoaPods recently (#29).

All I really care about is:

- I can build and test RxGRDB on OSX and iOS
- run the demo app
- lock the RxGRDB repo with specific versions of dependencies (so that I know what's inside a fresh RxGRDB clone)
- temporarily use dependency branches (future versions of GRDB or RxSwift)
- temporarily use local versions of dependencies (locally modified versions of GRDB or RxSwift)
- provide installation documentation that is reliable.

That's all 😅

CocoaPods shines at providing a solution for all those needs. There maybe is another way?

**Comment by groue** [comment] 2018-04-25 18:13
> I wonder if there is a way to make cocoapod's build pipeline "optional"

What about another target in the RxGRDB project?

**Comment by groue** [comment] 2018-04-25 18:29
I added "test installation methods" in my wish-list above. I like to hit the publish button with a relaxed minid. RxGRDB is surely less complex than GRDB, which needs [a lot of tests](https://travis-ci.org/groue/GRDB.swift/builds/370077386), but I got used to this extra safety!

**Comment by kluufger** [comment] 2018-04-25 18:37
@groue 

> I'd be happy to know why you don't... simply use CocoaPods.

They don't seem to support playgrounds, which I use as "scratchpads" to substitute REPLs in other languages.

**Comment by groue** [comment] 2018-04-25 18:53
> I'm quite new to Swift and iOS in general ...

Welcome on board!

There is a playground right into the RxGRDB workspace itself, at the very top: you may try it (build the RxGRDBmacOS target first)!

**Comment by groue** [comment] 2018-04-25 19:02
I'll lock at other RxSwiftCommunity projects. There may be one that has found a solution.

**Comment by groue** [comment] 2018-04-25 19:48
Those are interesting videos, produced by very active and valuable members of the community. There's much to learn from objc.io, their personal Twitter accounts, their posts in the [Swift forums](http://forums.swift.org), etc. A great source of inspiration.

I admit I lack the time, opportunity, and talent, to work in the same way. This shows in the way I ship my libs: they come with *requirements* 🤓. This is a way to avoid overpromises: not everybody can afford to engage in roads that turn into experimental dead-ends.

But this is not the end of the story. Those are questions like yours that make software better. As I said, I'll look at other libraries to see how they deal with their dependencies.

**Comment by groue** [comment] 2018-04-26 11:16
Maybe related: https://github.com/CocoaPods/CocoaPods/issues/7689

**Comment by groue** [comment] 2018-10-31 07:40
@kluufger: I could not find any solution, and have actually stopped searching a while ago. I close this issue. But I'm open to any solution if one eventually emerges!

**Closed by groue** 2018-10-31 07:40 UTC
